# Generated by Django 4.2 on 2026-05-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellaapp', '0002_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
